define({
	"profile_phrs": "Profile",
	"roles_phrs": "Roles",
	"username_phrs": "Username",
    "password_phrs": "Password",
    "rememberme_phrs": "Remember Me",
    "login_phrs": "Login",
    "session_phrs": "Session variables",
    "quick-play_sntc": "Quick play as guest",
    "alive_verb": "Alive",
    "time-elapsed_phrs": "Time elapsed:",
    "points_phrs": "Points:",
    "general-player_phrs": "General player",
    "administrator_phrs":  "Administrator",
    "moderator_phrs": "Moderator",
    "frontend-webdev_phrs": "Front end web developer",
    "backend-webdev_phrs": "Back end web developer",
    "graphic-designer_phrs": "Graphic designer",
    "audio-engineer_phrs": "Audio Engineer",
    "database-manager_phrs": "Database manager",
    "owner_phrs": "Owner"
});