define({
	"highscores_phrs": "Highscores",
	"endless-survival_phrs": "Endless survival",
	"story-mode_phrs": "Story mode",
	"survival-game_phrs": "Survival game",
	"name_noun": "Name",
	"playing-as_phrs": "Playing as",
    "rounds_phrs": "Rounds",
    "kills_phrs": "Kills",
    "assists_phrs": "Assists",
    "downs_phrs": "Downs",
    "revives_phrs": "Revives",
    "played-for_phrs": "Played for",
    "death-by_phrs": "Death by",
    "difficulty_phrs": "Difficulty",
    "chapter_phrs": "Chapters",
    "human-kills_phrs": "Human Kills",
    "alien-kills_phrs": "Alien Kills",
    "cause-of-death_phrs": "Cause of death",
    "close-verb": "Close"
});