define({
	"highscores_phrs": "ハイスコア",
	"endless-survival_phrs": "無限の生存",
	"story-mode_phrs": "ストーリーモード",
	"survival-game_phrs": "サバイバルゲーム",
	"name_noun": "名前",
	"playing-as_phrs": "として活躍",
    "rounds_phrs": "ラウンド",
    "kills_phrs": "殺す",
    "assists_phrs": "アシスト",
    "downs_phrs": "浮き沈み",
    "revives_phrs": "蘇る",
    "played-for_phrs": "のために遊んだ",
    "death-by_phrs": "死によって",
    "difficulty_phrs": "難しさ",
    "chapter_phrs": "チャプター",
    "human-kills_phrs": "人間殺す",
    "alien-kills_phrs": "エイリアンは殺す",
    "cause-of-death_phrs": "死因",
    "close-verb": "閉じる"
});