define({
	"controls_heading_noun": "Controls",
    "controls_heading_phrs": "Manage Controls",
    "screens_phrs": "Screens",
    "player_phrs": "Player",
    "weapons_phrs": "Weapons",
    "or_phrs": "OR",
    "mouse_noun": "mouse",
    "press_verb": "Press",
    "hold_verb": "Hold",
    "close_verb": "Close",
    "toggle-points_phrs": "to toggle points",
    "toggle-profile_phrs": "to toggle profile",
    "move-up_phrs": "to move up",
    "move-left_phrs": "to move left",
    "move-down_phrs": "to move down",
    "move-right_phrs": "to move right",
    "pickup_phrs": "to pickup an item",
    "to-shoot_phrs": "to shoot",
    "to-punch_phrs": "to punch",
    "to-throw-away-mag_phrs": "to throw away mag",
    "to-enter-new-mag_phrs": "to enter new mag",
    "to-reconnect-new-mag_phrs": "to reconnect new mag",
    "to-chamber_phrs": "to chamber"
});