define({
	"controls_heading_noun": "コントロール",
    "controls_heading_phrs": "コントロールを管理",
    "screens_phrs": "画面",
    "player_phrs": "プレーヤー",
    "weapons_phrs": "兵器",
    "or_phrs": "または",
    "mouse_noun": "コンピューターのマウス",
    "press_verb": "圧す",
    "hold_verb": "保つ",
    "close_verb": "閉じる",
    "toggle-points_phrs": "ポイントを切り替えることができ",
    "toggle-profile_phrs": "プロファイルを切り替えるには",
    "move-up_phrs": "上に移動する",
    "move-left_phrs": "左に移動する",
    "move-down_phrs": "下に移動する",
    "move-right_phrs": "右に移動する",
    "pickup_phrs": "アイテムを拾うために",
    "to-shoot_phrs": "撮影する",
    "to-punch_phrs": "穴を開ける",
    "to-throw-away-mag_phrs": "雑誌を捨てる",
    "to-enter-new-mag_phrs": "新しい雑誌を入力する",
    "to-reconnect-new-mag_phrs": "新しい雑誌を再接続する",
    "to-chamber_phrs": "室へ"
});